; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; platformio.ini

[env]
platform = espressif32
framework = espidf
monitor_speed = 115200
; Universal port wildcard so it flashes on both Windows and Linux instantly
upload_port = *
monitor_port = *

; --- BOARD 1: First Standard ESP32 ---
[env:esp32_node_a]
board = esp32dev

; --- BOARD 2: Second Standard ESP32 ---
[env:esp32_node_b]
board = esp32dev

; --- BOARD 3: ESP32-S3 Board ---
[env:esp32_s3_node]
board = esp32-s3-devkitc-1

; --- BOARD 4: Seeed Studio Xiao ESP32-C6 ---
[env:seeed_c6_node]
board = esp32-c6-devkitc-1

